// Native Codex profiles point to canonical HAWS roles; no model or tool overrides.
import { lstatSync, readFileSync, mkdirSync, writeFileSync, unlinkSync, renameSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { homedir } from 'node:os';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseArgs } from 'node:util';

try {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      source: { type: 'string' },
      'codex-home': { type: 'string' },
      'dry-run': { type: 'boolean', default: false },
    },
  });
  const [command = 'check'] = positionals;
  if (positionals.length > 1 || !['install', 'check', 'uninstall'].includes(command)) {
    throw new Error('Usage: haws.sh codex-agents install|check|uninstall [--dry-run] [--source PATH] [--codex-home PATH]');
  }
  const source = resolve(values.source || join(dirname(fileURLToPath(import.meta.url)), '../..'));
  const target = join(resolve(values['codex-home'] || process.env.CODEX_HOME || join(homedir(), '.codex')), 'agents');
  const stat = path => {
    try { return lstatSync(path); } catch (error) {
      if (error.code === 'ENOENT') return undefined;
      throw error;
    }
  };
  const directory = stat(target);
  if (directory && (!directory.isDirectory() || directory.isSymbolicLink())) {
    throw new Error(`Preserving non-directory or linked agent directory: ${target}`);
  }
  const manifestPath = join(dirname(target), 'haws-agents.json');
  const manifestStat = stat(manifestPath);
  if (manifestStat && (!manifestStat.isFile() || manifestStat.isSymbolicLink())) {
    throw new Error(`Preserving linked or non-file ownership record: ${manifestPath}`);
  }
  const manifest = manifestStat ? JSON.parse(readFileSync(manifestPath, 'utf8')) : { version: 1, hashes: {} };
  if (manifest.version !== 1 || !manifest.hashes || typeof manifest.hashes !== 'object') {
    throw new Error(`Unrecognized ownership record: ${manifestPath}`);
  }
  const hash = content => createHash('sha256').update(content).digest('hex');
  const roles = ['backend-engineer', 'frontend-engineer', 'organizer', 'researcher', 'tester'];
  const plans = roles.map(name => {
    const rolePath = join(source, 'agents', `${name}.md`);
    const markdown = readFileSync(rolePath, 'utf8');
    const frontmatter = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---/u)?.[1];
    if (!frontmatter || !frontmatter.split(/\r?\n/u).includes(`name: ${name}`)) {
      throw new Error(`Invalid canonical HAWS role: ${rolePath}`);
    }
    const description = frontmatter.match(/^description: (.+)$/mu)?.[1].trim();
    if (!description) throw new Error(`Missing role description: ${rolePath}`);
    const pathText = path => path.replaceAll('\\', '/');
    const instructions = [
      `You are the HAWS ${name} specialist.`,
      `Before acting, read your canonical role: ${pathText(rolePath)}.`,
      `Read applicable standards: ${pathText(join(source, 'core/HAWS.md'))} and ${pathText(join(source, 'core/WORK_INSTRUCTIONS.md'))}.`,
      `Read the optional personal DEV overlay under ${pathText(join(source, 'secondbrain'))} when present; otherwise use neutral starters under ${pathText(join(source, 'templates', 'secondbrain'))}.`,
      'Accept a bounded <task_assignment> from the main agent. Use only the tools actually available in this Codex session; the role YAML is not Codex configuration.',
      'Choose relevant installed skills, open their SKILL.md before using them, and execute their methodology. Use the skill catalog and ~/.agents/skills for discovery.',
      'Return <task_report> with results, command evidence, skills actually used, and [Unverified] limitations. Report questions to the main agent, who communicates with the user.',
      'Follow the canonical role scope. Never push without explicit user authorization. Inherit the parent model, effort, permissions, and available tools.',
    ].join('\n');
    const content = '# Generated by HAWS codex-agents. Edit canonical agents/*.md instead.\n'
      + `name = ${JSON.stringify(name)}\ndescription = ${JSON.stringify(description)}\n`
      + (name === 'researcher' ? 'sandbox_mode = "read-only"\n' : '')
      + `developer_instructions = ${JSON.stringify(instructions)}\n`;
    const path = join(target, `${name}.toml`);
    const existing = stat(path);
    const previous = existing?.isFile() && !existing.isSymbolicLink() ? readFileSync(path, 'utf8') : undefined;
    const same = previous === content;
    const owned = previous !== undefined && manifest.hashes[name] === hash(previous);
    return { name, path, content, existing, same, owned, previous };
  });
  // Preflight every destination before mutating any of them. Even edited generated
  // files are preserved: a comment alone is insufficient evidence of ownership.
  const conflicts = plans.filter(plan => plan.existing && !plan.same && !plan.owned);
  if (conflicts.length) throw new Error(`Preserving conflicting or edited profiles: ${conflicts.map(plan => plan.path).join(', ')}`);
  if (command === 'check') {
    const missing = plans.filter(plan => !plan.same);
    if (missing.length) throw new Error(`Missing Codex profiles: ${missing.map(plan => plan.name).join(', ')}`);
    console.log('PASS: 5/5 native Codex HAWS profiles match canonical sources.');
  } else {
    const pending = plans.filter(plan => command === 'install' ? !plan.same : plan.same || plan.owned);
    if (!values['dry-run'] && (pending.length || (command === 'install' && !manifestStat))) {
      if (command === 'install') mkdirSync(target, { recursive: true });
      const changed = [];
      const temporaryManifest = `${manifestPath}.tmp-${process.pid}`;
      try {
        for (const plan of pending) {
          if (command === 'install') {
            writeFileSync(plan.path, plan.content, { encoding: 'utf8', flag: plan.existing ? 'w' : 'wx' });
          } else {
            unlinkSync(plan.path);
          }
          changed.push(plan);
        }
        if (command === 'install') {
          const next = { version: 1, hashes: Object.fromEntries(plans.map(plan => [plan.name, hash(plan.content)])) };
          writeFileSync(temporaryManifest, JSON.stringify(next, null, 2) + '\n', { encoding: 'utf8', flag: 'wx' });
          renameSync(temporaryManifest, manifestPath);
        } else if (manifestStat) unlinkSync(manifestPath);
      } catch (error) {
        for (const plan of changed.reverse()) {
          if (plan.previous === undefined) unlinkSync(plan.path);
          else writeFileSync(plan.path, plan.previous, 'utf8');
        }
        if (stat(temporaryManifest)) unlinkSync(temporaryManifest);
        throw error;
      }
    }
    console.log(`${values['dry-run'] ? 'DRY-RUN' : 'OK'}: ${command} ${pending.length} Codex profiles (${target}).`);
  }
} catch (error) {
  console.error(`HAWS Codex agents: ${error.message}`);
  process.exitCode = 1;
}
